services:
  - type: web
    name: hsqe-system
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app.application:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/src/app/hsqe.db
      - key: FLASK_ENV
        value: production
    healthCheckPath: /login
